# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - vivx

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_5d3ca608ead649aa80b203607ea26e05 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1e4d72de035f4579bb61f25c7dbacc5a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5d3ca608ead649aa80b203607ea26e05 }}/thiemisoubhia/vivx:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'vivx'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7f6ed025754c43c1adf25d87359b8db9 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5d3ca608ead649aa80b203607ea26e05 }}/thiemisoubhia/vivx:${{ github.sha }}'