# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - vivx

on:
  push:
    branches:
      - teste3
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_d157845c7e894bba88b1ce36d3789e82 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_412b1530a6d84c08b6766dc3b02419e7 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d157845c7e894bba88b1ce36d3789e82 }}/thiemisoubhia/teste:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'vivx'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9ce70e9d8d54492e91e57c784985eca9 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d157845c7e894bba88b1ce36d3789e82 }}/thiemisoubhia/teste:${{ github.sha }}'